- name: Create the dotfiles directory
  file:
    state: directory
    path: "{{ item }}"
    recurse: true
  with_items:
    - "{{ scratchDir }}"

- name: Setup config files
  file:
    state: link
    src: "{{ role_path }}/files/{{ item.key }}"
    dest: "{{ item.value }}"
  with_dict:
    bash_profile: ~/.bash_profile
    gitconfig: ~/.gitconfig
    hgrc: ~/.hgrc
    inputrc: ~/.inputrc
    tmux.conf: ~/.tmux.conf
    ncmpcpp/: ~/.ncmpcpp
    mutt: ~/.mutt
    muttrc: ~/.muttrc
    htop: ~/.config/htop
    fontconfig: ~/.config/fontconfig

- name: Template out the bashrc file
  template:
    src: bashrc.j2
    dest: ~/.bashrc


- name: Install trapd00r's dircolors
  git:
    accept_hostkey: yes
    dest: ~/.lscolors
    repo: https://github.com/trapd00r/LS_COLORS.git

- name: Check if rupa/z is installed
  register: rupa_z
  stat:
    path: ~/.rupa_z
    get_checksum: false
    get_md5: false

- name: Clone rupa_z
  when: not rupa_z.stat.exists
  git:
    accept_hostkey: yes
    dest: ~/.rupa_z
    repo: https://github.com/WishCow/z.git

- name: Install vim config
  git:
    accept_hostkey: yes
    dest: ~/.vim
    repo: git@github.com:WishCow/VimConfig.git
  notify:
    - Refresh vim plugins

- name: Symlink .vimrc to .vim/vimrc
  file:
    state: link
    src: ~/.vim/.vimrc
    path: ~/.vimrc

- name: Clone the scripts repository
  git:
    accept_hostkey: yes
    dest: ~/bin
    repo: git@github.com:WishCow/scripts.git

- name: Clone tmux plugins
  git:
    accept_hostkey: yes
    dest: "{{ scratchDir }}/{{ item.key }}"
    repo: "{{ item.value }}"
  with_dict:
    tmux-yank: https://github.com/tmux-plugins/tmux-yank
    tmux-copycat: https://github.com/tmux-plugins/tmux-copycat
