# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$\[\e[m\] '
PS2='> '
PS3='> '
PS4='+ '

PROMPT_COMMAND="prompt_command"

prompt_command() {
    # Save history after each command
    history -a

    # Append user@host:host to shell windows if running rxvt
    [[ $TERM =~ rxvt ]] && printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"

    # If we are running under tmux, set the current dir in an env variable
    if [ -n "$TMUX" ]; then
        tmux setenv -g "TMUX_PWD_$(tmux display -p "#D")" "$PWD"
    fi
}

# Append to history
shopt -s histappend

# Multiline commands take only 1 line
shopt -s cmdhist

# Extended globbing (**)
shopt -s extglob

# Star matches dotfiles
shopt -s globstar

# Recheck window size after each command
shopt -s checkwinsize

# Avoid overwriting files with redirections (>)
set -o noclobber

# Disable CTRL-s freezing/CTRL-q starting program flow
stty stop ""

# Pathname expansion will be treated as case-insensitive
shopt -s nocaseglob

[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh
