graphical_packages:
  - feh
  - firefox
  - mupdf
  - pavucontrol
  - ponymix
  - pulseaudio
  - pulseaudio-alsa
  - slock
  - thunar
  - tumbler
  - xsel
  - xorg-xrdb
  - xorg-xmodmap
  - ttf-inconsolata
  - mate-notification-daemon
urxvt_autocomplete_dir: ~/.urxvt/ext/ac
aur_packages:
  - rxvt-unicode-pixbuf
  - fbxkb
  - pasystray
  - xcape
