- name: Install common packages
  sudo: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items: packages

- name: Create root .vim/plugin directory
  sudo: yes
  file:
    path: ~/.vim/plugin
    state: directory

- name: Copy root's vimrc
  sudo: yes
  copy:
    src: root.vimrc
    dest: ~/.vim/plugin/defaults.vim
