- name: Install common packages
  sudo: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items: packages

- name: Create some config directories
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - ~/.vim/plugin
    - ~/.config/htop

- name: Copy some config files
  sudo: yes
  copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
  with_dict:
    root.vimrc: ~/.vim/plugin/defaults.vim
    htoprc: ~/.config/htop/htoprc
