#!/bin/bash

PATH+=:~/bin


has() {
    which "$1" &>/dev/null
}

xrdb -merge ~/.Xresources
xset -dpms
xset s off off
numlockx
fbxkb &
xset m 3/1 &
~/bin/wallpaper.sh &

if has pasystray; then
    pasystray &
fi

if has mpd; then
    mpd &
fi

if has xautolock; then
    xautolock &
fi

~/bin/keyboard.sh

[ -f ~/.xinitrc_local ] && . ~/.xinitrc_local
exec startfluxbox
