#!/bin/bash

has() {
    which "$1" &>/dev/null
}

xrdb -merge ~/.Xresources
setxkbmap -layout hu,no,us -option grp:alt_shift_toggle
xset -dpms
xset s off off
numlockx
fbxkb &
xset m 3/1 &
~/bin/wallpaper.sh &

if has pasystray; then
    pasystray &
fi

if has mpd; then
    mpd &
fi

if has xautolock; then
    xautolock &
fi

xmodmap ~/.xmodmap
xcape -e Control_L=Escape -t 120

[ -f ~/.xinitrc_local ] && . ~/.xinitrc_local
exec startfluxbox
