#!/bin/bash

has() {
    which "$1" &>/dev/null
}

xrdb -merge ~/.Xresources
setxkbmap -layout hu,us,no -option grp:alt_shift_toggle,caps:swapescape
xset -dpms
xset s off off
numlockx
fbxkb &
xset m 3/1 &
~/bin/wallpaper.sh &

if has pasystray; then
    pasystray &
fi

if has mpd; then
    mpd &
fi

if has dunst; then
    dunst &
fi

. ~/.xinitrc_local
exec startfluxbox
