- name: Install common packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: packages

- name: Install config files
  with_dict:
    gitconfig: ~/.gitconfig
    Xresources: ~/.Xresources
    ackrc: ~/.ackrc
    hgrc: ~/.hgrc
    inputrc: ~/.inputrc
    'tmux.conf': ~/.tmux.conf
    feh: ~/.config/
    ncmpcpp/: ~/.ncmpcpp
    mutt/: '{{ dotdir }}/mutt'
    compton.conf: ~/.config/compton.conf
    dunstrc: ~/.config/dunst/dunstrc
    xinitrc: ~/.xinitrc

  copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"

- name: Install urxvt autocomplete
  git:
    accept_hostkey: yes
    dest: "{{ dotdir }}/ac"
    repo: https://github.com/Vifon/autocomplete-ALL-the-things.git

- name: Create the .urxvt/ext directory
  file:
    path: ~/.urxvt/ext
    recurse: yes
    state: directory

- name: Symlink urxvt autocomplete under ~/.urxvt
  file:
    path: "~/.urxvt/ext/autocomplete"
    state: link
    src: "{{ dotdir }}/ac/autocomplete-ALL-the-things"

- name: Install vim config
  git:
    accept_hostkey: yes
    dest: ~/.vim
    repo: git@github.com:WishCow/VimConfig.git

- name: Symlink .vimrc to .vim/vimrc
  file:
    state: link
    src: ~/.vim/.vimrc
    path: ~/.vimrc

- name: Symlink muttrc
  file:
    state: link
    src: '{{ dotdir }}/mutt/muttrc'
    path: ~/.muttrc
